remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: "Code Cards"
description: "Study tool for programming with flashcards, quizzes, and more!"
gitorg: "https://github.com/rjawesome/team-8-frontend"
google_analytics:
